//@version=5
strategy("NY 1H Start – 5m First Candle (VWAP)", overlay=true, initial_capital=100000, default_qty_type=strategy.percent_of_equity, default_qty_value=1)

var float firstHigh = na
var float firstLow  = na
var bool  firstBull = false
var bool  traded    = false

// VWAP
vwapValue = ta.vwap(close)

// NEW YORK SESSION
nySession = "1800-2359"
inNY = not na(time(timeframe.period, nySession, "Asia/Karachi"))

// NEW HOUR
isNewHour = ta.change(time("60")) != 0
barsSinceHour = ta.barssince(isNewHour)

if isNewHour
    firstHigh := na
    firstLow := na
    firstBull := false
    traded := false

// FIRST 5m candle
if barsSinceHour == 0
    firstHigh := high
    firstLow := low
    firstBull := close > open

risk = firstHigh - firstLow

// LONG (VWAP filter)
if barsSinceHour == 0 and not traded and firstBull and inNY and close > vwapValue
    strategy.entry("Long", strategy.long)
    strategy.exit("LongExit", "Long", stop=firstLow, limit=close + risk * 2)
    traded := true

// SHORT (VWAP filter)
if barsSinceHour == 0 and not traded and not firstBull and inNY and close < vwapValue
    strategy.entry("Short", strategy.short)
    strategy.exit("ShortExit", "Short", stop=firstHigh, limit=close - risk * 2)
    traded := true
